version: '3.7'

services:
  nrsc5:
    image: ghcr.io/foxxmd/nrsc5-rtlsdr-icecast
    container_name: nrsc5
    environment:
      - RADIO_STATION=90.1
      #- CHANNEL=1
      #- AUDIO_FORMAT=MP3
      - ICECAST_URL=localhost:8000/myradio
      - ICECAST_PWD=hackme
    devices:
      - "/dev/bus/usb/005/006"