version: "3.3"
services:
  icecast:
    image: moul/icecast
    container_name: icecast
    restart: always
    network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${PWD}/icecast.xml:/etc/icecast2/icecast.xml
    ports:
      - 8000:8000
services:
  nrsc5:
    build: .
    container_name: nrsc5
    restart: always
    privileged: true
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
